---
- name: Create templates directory
  file:
    path: /home/emmanuel/repogit/UTNFRA_SO_2do_Parcial_Martin/202406/ansible/roles/2do_parcial/templates
    state: directory
    mode: '0755'

- name: Create student template
  copy:
    content: |
      Nombre: Emmanuel
      Apellido: Martin
      Division: 115
    dest: /home/emmanuel/repogit/UTNFRA_SO_2do_Parcial_Martin/202406/ansible/roles/2do_parcial/templates/datos_alumno.txt.j2

- name: Get IP address
  command: curl -s ifconfig.me
  register: ip_address

- name: Get distribution info
  shell: lsb_release -d | sed 's/Description:\s*//'
  register: distribution_info

- name: Get number of cores
  command: nproc
  register: num_cores

- name: Create pc template
  copy:
    content: |
      Ip: {{ ip_address.stdout }}
      Distribucion: {{ distribution_info.stdout }}
      Cantidad_de_cores: {{ num_cores.stdout }}
    dest: /home/emmanuel/repogit/UTNFRA_SO_2do_Parcial_Martin/202406/ansible/roles/2do_parcial/templates/datos_equipo.txt.j2
