---
# tasks file for 2do_parcial

- debug:
    msg: "Tareas del 2do Parcial"

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

- name: Create student file data
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
  vars:
    student_name: "Emmanuel"
    student_lastName: "Martín"
    student_class: "115"

- name: Create pc file data
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
  vars:
    pc_ip: "190.49.109.151"
    pc_distribution: "Description:	Ubuntu 24.04.1 LTS"
    pc_cores: "5"

- name: Set permissions 2PSupervisores
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%2PSupervisores'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
